name: Muaythai
favicon: null
layout_spectrum: 0.9330658339895308
typography_spectrum: 0.2996672198642045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.06504356721416116
  lightness: 0.15204135398380458
  saturation: 0.17343241861090064
  rhythmicContrast: 0.6663960933219641
purpose: []
